# .github/workflows/sync-workspace-on-merge.yml
name: Sync Databricks Workspace on PR Merge

on:
  push:
    branches:
      - dev  # Trigger on push to dev (after PR merge)

jobs:
  sync_workspace:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Databricks CLI for dev environment
        run: |
          echo "Setting up Databricks CLI for dev environment"
          echo "[DEFAULT]" > ~/.databricks-cli/config
          echo "host = ${{ secrets.DATABRICKS_HOST_DEV }}" >> ~/.databricks-cli/config
          echo "token = ${{ secrets.DATABRICKS_TOKEN_DEV }}" >> ~/.databricks-cli/config

      - name: Call Reusable Databricks CI/CD Workflow for Dev
        uses: ./.github/workflows/reusable_databricks.yml  # Path to the reusable workflow
        with:
          environment: dev  # Sync with the dev environment
          notebook_path: notebooks/**  # Path to the notebook to upload
          databricks_path: /Shared/**  # Path in the Databricks workspace
        secrets:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST_DEV }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN_DEV }}
