# .github/workflows/sync-workspace-on-merge.yml
name: Sync Databricks Workspace on PR Merge

on:
  push:
    branches:
      - feature/test  # Trigger on push to dev (after PR merge)

jobs:
  sync_workspace:
    uses: ./.github/workflows/reusable-databricks.yml  # Path to the reusable workflow
    with:
      environment: dev  # Sync with the dev environment
      notebook_path: notebooks/**  # Path to the notebook to upload
      databricks_path: /Shared/folder/ # Path in the Databricks workspace
      repo_path: /Repos/vaishnavi@tigeranalytics.com/databricks
      repo_branch: feature/test
    secrets:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
