name: Sync Databricks Workspace on PR Merge

on:
  push:
    branches:
      - dev  # Trigger when changes are pushed to dev branch (after PR merge)

jobs:
  sync_workspace:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Call Reusable Databricks CI/CD Workflow
        uses: ./.github/workflows/reusable_databricks.yml  # Adjust path if needed
        with:
          environment: dev  # Sync with the dev environment
          notebook_path: notebooks/**  # Path to the notebook to upload
          databricks_path: /Shared/**  # Path in the Databricks workspace
        secrets:
          DATABRICKS_HOST_DEV: ${{ secrets.DATABRICKS_HOST_DEV }}
          DATABRICKS_TOKEN_DEV: ${{ secrets.DATABRICKS_TOKEN_DEV }}
          DATABRICKS_HOST_TEST: ${{ secrets.DATABRICKS_HOST_TEST }}
          DATABRICKS_TOKEN_TEST: ${{ secrets.DATABRICKS_TOKEN_TEST }}
