# .github/workflows/reusable-databricks.yml

name: Reusable Databricks CI/CD AWS Workflow

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      notebook_path:
        required: true
        type: string
      databricks_path:
        required: true
        type: string
    secrets:
      DATABRICKS_HOST:
        required: true
      DATABRICKS_TOKEN:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Databricks CLI
        run: pip install databricks-cli --upgrade  # Ensure the latest version

      - name: Configure Databricks CLI using environment variables
        run: |
          export DATABRICKS_HOST_DEV=${{ secrets.DATABRICKS_HOST }}
          export DATABRICKS_TOKEN_DEV=${{ secrets.DATABRICKS_TOKEN }}
      - name: Upload notebook to Databricks ${{ inputs.environment }}
        run: |
          databricks workspace import ${{ inputs.notebook_path }} ${{ inputs.databricks_path }} --language PYTHON --overwrite
