# .github/workflows/reusable-databricks.yml

name: Reusable Databricks CI/CD AWS Workflow

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      notebook_path:
        required: true
        type: string
      databricks_path:
        required: true
        type: string
    secrets:
      DATABRICKS_HOST:
        required: true
      DATABRICKS_TOKEN:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Databricks CLI
        run: pip install databricks-cli

      - name: Configure Databricks CLI
        run: |
          databricks configure --host ${{ secrets.DATABRICKS_HOST }} --token ${{ secrets.DATABRICKS_TOKEN }}

      - name: Upload notebook to Databricks ${{ inputs.environment }}
        run: |
          databricks workspace import ${{ inputs.notebook_path }} ${{ inputs.databricks_path }} --language PYTHON --overwrite
